# Generated by Django 4.2.5 on 2023-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="statistic",
            index=models.Index(
                fields=["resource", "attribute"], name="stats_stati_resourc_097158_idx"
            ),
        ),
    ]
