version: "3.8"
name: "nekosauce"
services:
  backend:
    build: ./src/backend
    command: "/bin/sh -c \"/app/run.sh\""
    depends_on:
      - database
      - redis
      - rabbitmq
    environment:
      BACKEND_GUNICORN_WORKERS: 1
      BACKEND_DRAMATIQ_WORKERS: 1
      BACKEND_DRAMATIQ_THREADS: 1
    ports:
      - "8000:8000"
    volumes:
      - static:/static
    restart: always
  frontend:
    build: ./src/frontend
    command: "npm run start"
    ports:
      - "3000:3000"
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nekosauce
      - POSTGRES_PASSWORD=nekosauce
      - POSTGRES_DB=nekosauce
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "nekosauce", "-U", "nekosauce"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_DEFAULT_USER: nekosauce
      RABBITMQ_DEFAULT_PASS: nekosauce
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5672:5672"
  nginx:
    image: nginx:1-alpine
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - ./src/nginx/nekosauce.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
volumes:
  database:
  static: