# Generated by Django 4.2.4 on 2023-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0003_alter_entity_options_alter_hash_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='direct_uploader',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='entity_ptr',
        ),
        migrations.RemoveField(
            model_name='artsauce',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artsauce',
            name='sauce_ptr',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='mangasauce',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='mangasauce',
            name='sauce_ptr',
        ),
        migrations.RemoveField(
            model_name='uploader',
            name='entity_ptr',
        ),
        migrations.AlterModelOptions(
            name='sauce',
            options={},
        ),
        migrations.RemoveField(
            model_name='hash',
            name='crop_resistant',
        ),
        migrations.RemoveField(
            model_name='sauce',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='sauce',
            name='uploaders',
        ),
        migrations.AlterField(
            model_name='hash',
            name='method',
            field=models.IntegerField(choices=[(0, 'Perceptual Hash'), (1, 'Average Hash'), (2, 'Differential Hash'), (3, 'Wavelet Hash')], default=0),
        ),
        migrations.DeleteModel(
            name='AnimeSauce',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='ArtSauce',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='MangaSauce',
        ),
        migrations.DeleteModel(
            name='Uploader',
        ),
    ]
