# Generated by Django 4.2.5 on 2023-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="donation",
            field=models.FloatField(
                choices=[
                    (0, "None"),
                    (3, "Supporter-chan"),
                    (5, "Senpai"),
                    (10, "Sama"),
                ],
                default=0,
            ),
        ),
    ]
