# Generated by Django 4.2.4 on 2023-09-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="donation",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="user",
            name="donation_date",
            field=models.DateTimeField(null=True),
        ),
    ]
