# Generated by Django 4.2.5 on 2023-09-08 04:09

from django.db import migrations, models
import nekosauce.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_donation_user_donation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                db_index=True,
                default=nekosauce.users.models.generate_api_key,
                max_length=86,
            ),
        ),
    ]
