# Generated by Django 4.2.4 on 2023-08-12 07:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True), size=None)),
                ('site_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), size=None)),
                ('api_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('api_docs', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sauce_type', models.CharField(choices=[('art', 'Art'), ('anime', 'Anime'), ('manga', 'Manga')], default='art', max_length=5)),
                ('site_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), size=None)),
                ('api_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=255), size=None)),
                ('file_url', models.URLField(max_length=255)),
                ('site_id', models.CharField(max_length=255)),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('ahash_8', models.CharField(blank=True, max_length=16, null=True)),
                ('ahash_16', models.CharField(blank=True, max_length=64, null=True)),
                ('ahash_32', models.CharField(blank=True, max_length=256, null=True)),
                ('ahash_64', models.CharField(blank=True, max_length=1024, null=True)),
                ('ahash_cr', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, max_length=6, size=None)),
                ('phash_8', models.CharField(blank=True, max_length=64, null=True)),
                ('phash_16', models.CharField(blank=True, max_length=256, null=True)),
                ('phash_32', models.CharField(blank=True, max_length=1024, null=True)),
                ('phash_64', models.CharField(blank=True, max_length=4096, null=True)),
                ('phash_cr', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, max_length=6, size=None)),
                ('dhash_8', models.CharField(blank=True, max_length=64, null=True)),
                ('dhash_16', models.CharField(blank=True, max_length=256, null=True)),
                ('dhash_32', models.CharField(blank=True, max_length=1024, null=True)),
                ('dhash_64', models.CharField(blank=True, max_length=4096, null=True)),
                ('dhash_cr', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, max_length=6, size=None)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauces.artist')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauces', to='sauces.source')),
            ],
        ),
    ]
