# Generated by Django 4.2.4 on 2023-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauce',
            name='identifier',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
