# Generated by Django 4.2.4 on 2023-08-20 04:09

import django.contrib.postgres.indexes
from django.db import migrations, models
import sauces.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0009_artist_sauces_sauce_is_nsfw"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hash16Bits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    )
                ),
                (
                    "algorithm",
                    models.IntegerField(
                        choices=[
                            (0, "Perceptual"),
                            (1, "Average"),
                            (2, "Differential"),
                            (3, "Wavelet"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "bits",
                    sauces.utils.fields.BitField(
                        max_length=256, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Hash (16 Bits)",
                "verbose_name_plural": "Hashes (16 Bits)",
            },
        ),
        migrations.CreateModel(
            name="Hash32Bits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    )
                ),
                (
                    "algorithm",
                    models.IntegerField(
                        choices=[
                            (0, "Perceptual"),
                            (1, "Average"),
                            (2, "Differential"),
                            (3, "Wavelet"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "bits",
                    sauces.utils.fields.BitField(
                        max_length=1024, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Hash (32 Bits)",
                "verbose_name_plural": "Hashes (32 Bits)",
            },
        ),
        migrations.CreateModel(
            name="Hash64Bits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    )
                ),
                (
                    "algorithm",
                    models.IntegerField(
                        choices=[
                            (0, "Perceptual"),
                            (1, "Average"),
                            (2, "Differential"),
                            (3, "Wavelet"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "bits",
                    sauces.utils.fields.BitField(
                        max_length=4096, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Hash (64 Bits)",
                "verbose_name_plural": "Hashes (64 Bits)",
            },
        ),
        migrations.CreateModel(
            name="Hash8Bits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    )
                ),
                (
                    "algorithm",
                    models.IntegerField(
                        choices=[
                            (0, "Perceptual"),
                            (1, "Average"),
                            (2, "Differential"),
                            (3, "Wavelet"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "bits",
                    sauces.utils.fields.BitField(
                        max_length=64, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Hash (8 Bits)",
                "verbose_name_plural": "Hashes (8 Bits)",
            },
        ),
        migrations.RemoveField(
            model_name="sauce",
            name="hashes",
        ),
        migrations.DeleteModel(
            name="Hash",
        ),
        migrations.AddIndex(
            model_name="hash8bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 0)), name="hash8_0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash8bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 1)), name="hash8_1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash8bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 2)), name="hash8_2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash8bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 3)), name="hash8_3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash64bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 0)), name="hash64_0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash64bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 1)), name="hash64_1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash64bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 2)), name="hash64_2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash64bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 3)), name="hash64_3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash32bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 0)), name="hash32_0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash32bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 1)), name="hash32_1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash32bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 2)), name="hash32_2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash32bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 3)), name="hash32_3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash16bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 0)), name="hash16_0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash16bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 1)), name="hash16_1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash16bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 2)), name="hash16_2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hash16bits",
            index=django.contrib.postgres.indexes.BTreeIndex(
                ["bits"], condition=models.Q(("algorithm", 3)), name="hash16_3_idx"
            ),
        ),
        migrations.AddField(
            model_name="sauce",
            name="hashes_16bits",
            field=models.ManyToManyField(related_name="sauces", to="sauces.hash16bits"),
        ),
        migrations.AddField(
            model_name="sauce",
            name="hashes_32bits",
            field=models.ManyToManyField(related_name="sauces", to="sauces.hash32bits"),
        ),
        migrations.AddField(
            model_name="sauce",
            name="hashes_64bits",
            field=models.ManyToManyField(related_name="sauces", to="sauces.hash64bits"),
        ),
        migrations.AddField(
            model_name="sauce",
            name="hashes_8bits",
            field=models.ManyToManyField(related_name="sauces", to="sauces.hash8bits"),
        ),
    ]
