# Generated by Django 4.2.4 on 2023-08-18 00:46

from django.db import migrations


def create_indexes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        for i in range(4 * 4):
            condition = "BIT_LENGTH(bits) = {bit_length} AND method = {method}".format(
                bit_length=2 ** (i // 4 + 3), method=i % 4
            )
            index_name = "hash_{}_{}_idx".format(i % 4, 2 ** (i // 4 + 3))
            sql = (
                "CREATE INDEX {index_name} ON sauces_hash USING btree (bits) "
                "WHERE {condition};".format(
                    index_name=index_name,
                    condition=condition,
                )
            )
            cursor.execute(sql)


def remove_indexes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        for i in range(4 * 4):
            index_name = "hash_{}_{}_idx".format(i % 4, 2 ** (i // 4 + 3))
            sql = "DROP INDEX IF EXISTS {index_name};".format(index_name=index_name)
            cursor.execute(sql)


class Migration(migrations.Migration):
    dependencies = [("sauces", "0009_artist_sauces_sauce_is_nsfw")]

    operations = [
        migrations.RunPython(create_indexes, remove_indexes),
    ]
