# Generated by Django 4.2.4 on 2023-08-18 01:16

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0010_auto_20230817_2146'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hash',
            name='hash_idx',
        ),
        migrations.AddField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
