# Generated by Django 4.2.4 on 2023-08-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0011_remove_artist_links_remove_artist_names_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
