# Generated by Django 4.2.5 on 2023-10-03 03:15

import django.contrib.postgres.indexes
from django.db import migrations, models
import nekosauce.sauces.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sauce",
            name="hash",
            field=nekosauce.sauces.utils.fields.BitField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="sauce",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Illustration"),
                    (2, "Illustration (Animated)"),
                    (3, "Manga"),
                    (4, "Doujinshi"),
                    (5, "Anime"),
                    (6, "Visual Novel"),
                    (7, "Light Novel"),
                    (8, "Other"),
                ],
                default=1,
            ),
        ),
        migrations.AddIndex(
            model_name="sauce",
            index=django.contrib.postgres.indexes.BTreeIndex(
                models.F("hash"),
                condition=models.Q(("hash__isnull", False)),
                name="sauces__hashes__idx",
            ),
        ),
    ]
