# Generated by Django 4.2.5 on 2023-10-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0002_sauce_sauces__source_site_id__idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sauce",
            name="source_site_id",
            field=models.CharField(max_length=255, verbose_name="(Source) ID"),
        ),
    ]
