# Generated by Django 4.2.4 on 2023-08-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0005_sauce_created_at_sauce_updated_at_alter_hash_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sauce",
            name="height",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="sauce",
            name="width",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="sauce",
            unique_together={("source", "source_site_id")},
        ),
    ]
