# Generated by Django 4.2.5 on 2023-10-07 15:37

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0006_alter_sauce_source_id_sauce_sauces__14_hashes__idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sauce",
            name="source_id",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Danbooru"),
                    (2, "Gelbooru"),
                    (3, "Konachan"),
                    (4, "AIBooru"),
                    (5, "Anime Pictures"),
                    (6, "ATFBooru"),
                    (7, "Lolibooru"),
                    (8, "Pixiv"),
                    (9, "Rule 34"),
                    (10, "Yande.re"),
                    (11, "Zerochan"),
                    (12, "Safebooru"),
                    (13, "TBIB"),
                    (14, "E-shuushuu"),
                    (15, "Xbooru"),
                    (16, "HypnoHub"),
                ],
                verbose_name="Source",
            ),
        ),
        migrations.AddIndex(
            model_name="sauce",
            index=django.contrib.postgres.indexes.BTreeIndex(
                models.F("hash"),
                condition=models.Q(("hash__isnull", False), ("source_id", 15)),
                name="sauces__15_hashes__idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sauce",
            index=django.contrib.postgres.indexes.BTreeIndex(
                models.F("hash"),
                condition=models.Q(("hash__isnull", False), ("source_id", 16)),
                name="sauces__16_hashes__idx",
            ),
        ),
    ]
