# Generated by Django 4.2.5 on 2023-10-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0007_alter_sauce_source_id_sauce_sauces__15_hashes__idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sauce",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="sauce",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Not Processed"), (1, "Processed"), (2, "Failed")],
                db_index=True,
                default=0,
            ),
        ),
    ]
