# Generated by Django 4.2.5 on 2023-10-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0008_remove_sauce_updated_at_sauce_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sauce",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Not processed"), (1, "Processed"), (2, "Failed")],
                db_index=True,
                default=0,
            ),
        ),
    ]
