# Generated by Django 4.2.5 on 2023-10-08 01:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0009_alter_sauce_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sauce",
            name="api_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
        migrations.AlterField(
            model_name="sauce",
            name="file_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
        migrations.AlterField(
            model_name="sauce",
            name="site_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
        migrations.AlterField(
            model_name="sauce",
            name="source_id",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Danbooru"),
                    (2, "Gelbooru"),
                    (3, "Konachan"),
                    (4, "AIBooru"),
                    (5, "Anime Pictures"),
                    (6, "ATFBooru"),
                    (7, "Lolibooru"),
                    (8, "Pixiv"),
                    (9, "Rule 34"),
                    (10, "Yande.re"),
                    (11, "Zerochan"),
                    (12, "Safebooru"),
                    (13, "TBIB"),
                    (14, "E-shuushuu"),
                    (15, "Xbooru"),
                    (16, "HypnoHub"),
                ],
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="sauce",
            name="source_site_id",
            field=models.TextField(verbose_name="(Source) ID"),
        ),
        migrations.AlterField(
            model_name="sauce",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
