# Generated by Django 4.2.5 on 2023-10-12 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0010_alter_sauce_api_urls_alter_sauce_file_urls_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__1_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__2_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__3_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__4_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__5_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__6_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__7_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__8_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__9_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__10_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__11_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__12_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__13_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__14_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__15_hashes__idx",
        ),
        migrations.RemoveIndex(
            model_name="sauce",
            name="sauces__16_hashes__idx",
        ),
    ]
