# Generated by Django 4.2.4 on 2023-08-21 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0014_sourcecache"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SourceCache",
        ),
    ]
