# Generated by Django 4.2.4 on 2023-09-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0015_delete_sourcecache'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hash16bits',
            unique_together={('bits', 'algorithm')},
        ),
        migrations.AlterUniqueTogether(
            name='hash32bits',
            unique_together={('bits', 'algorithm')},
        ),
        migrations.AlterUniqueTogether(
            name='hash64bits',
            unique_together={('bits', 'algorithm')},
        ),
        migrations.AlterUniqueTogether(
            name='hash8bits',
            unique_together={('bits', 'algorithm')},
        ),
    ]
