# Generated by Django 4.2.4 on 2023-09-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0016_alter_hash16bits_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauce',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
