# Generated by Django 4.2.5 on 2023-09-11 05:04

from django.db import migrations, models
import django.db.models.deletion
import nekosauce.sauces.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0023_remove_sauce_hash_delete_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hash",
            fields=[
                (
                    "bits",
                    nekosauce.sauces.utils.fields.BitField(
                        editable=False,
                        max_length=1024,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hash",
                "verbose_name_plural": "Hashes",
            },
        ),
        migrations.AddField(
            model_name="sauce",
            name="hash",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sauces",
                to="sauces.hash",
            ),
        ),
    ]
