# Generated by Django 4.2.5 on 2023-09-11 05:10

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauces', '0024_hash_sauce_hash'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sauce',
            index=django.contrib.postgres.indexes.BTreeIndex(models.F('hash'), models.F('source'), name='sauces__hash_source__idx'),
        ),
    ]
