# Generated by Django 4.2.5 on 2023-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0025_sauce_sauces__hash_source__idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hash",
            index=models.Index(fields=["-bits"], name="hash_bits_idx"),
        ),
    ]
