# Generated by Django 4.2.5 on 2023-09-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0027_source_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sauce",
            name="is_nsfw",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
