# Generated by Django 4.2.5 on 2023-09-29 02:18

from django.db import migrations, models
import nekosauce.sauces.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sauces", "0027_source_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="hash",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hash",
            name="bits",
            field=nekosauce.sauces.utils.fields.BitField(
                editable=False, max_length=1024, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sauce",
            name="is_nsfw",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
